# Generated by Django 2.2.1 on 2019-08-11 17:41

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('empMast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FromModelClass',
        ),
    ]
