# Generated by Django 2.2.1 on 2019-08-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empMast', '0002_auto_20190811_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodelclass',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='usermodelclass',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
