from django.db import models

class RegistrationModelClass(models.Model):
    userName = models.CharField(max_length=30)
    password = models.CharField(max_length=20)

class FromModelClass(models.Model):
    user_id =models.PositiveIntegerField(blank=True)
    first_name= models.CharField(max_length=255)
    middle_name= models.CharField(max_length=255, null=False)
    last_name= models.CharField(max_length=255)
    full_name = models.CharField(max_length=255)
    gender =models.CharField(max_length=1)
    email_address=models.CharField(max_length=100)
    user_name = models.CharField(max_length=50)
    user_password =models.CharField(max_length=50)
    is_active = models.CharField(max_length=1)
    login_id =models.PositiveIntegerField()
    start_date = models.DateField(blank=True)
    end_date= models.DateField(blank=True)
    created_by = models.PositiveIntegerField()
    creation_date = models.DateField(blank=True)
    last_updated_by= models.PositiveIntegerField()
    last_updated_date =models.DateField(blank=True)
    attribute1 = models.CharField(max_length=255, null=False)
    attribute2 = models.CharField(max_length=255, null=False)
    attribute3 = models.CharField(max_length=255, null=False)
    attribute4 = models.CharField(max_length=255, null=False)
    attribute5 = models.CharField(max_length=255, null=False)
    attribute6 = models.CharField(max_length=255, null=False)
    attribute7 = models.CharField(max_length=255, null=False)
    attribute8 = models.CharField(max_length=255, null=False)
    attribute9 = models.CharField(max_length=255, null=False)
    attribute10 = models.CharField(max_length=255, null=False)
