# Generated by Django 2.2.1 on 2019-10-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'female')], max_length=1, null=True)),
                ('systolic_BP', models.PositiveIntegerField()),
                ('diastolic_BP', models.PositiveIntegerField()),
                ('smoking_years', models.PositiveIntegerField()),
                ('no_of_packs', models.PositiveIntegerField()),
                ('fasting_blood_sugar', models.PositiveIntegerField()),
                ('hypothyroid', models.BooleanField(default=True)),
                ('obese', models.PositiveIntegerField()),
                ('intravenous_drug_abuse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patientguidelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('recommendation', models.CharField(max_length=30)),
                ('conditions', models.CharField(max_length=30)),
                ('references', models.CharField(max_length=30)),
            ],
        ),
    ]
