# Generated by Django 2.0.5 on 2019-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0002_auto_20191001_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='obese',
            field=models.BooleanField(default=False),
        ),
    ]
