# Generated by Django 2.2.1 on 2019-10-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0003_auto_20191002_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientguidelines',
            old_name='name',
            new_name='Patient',
        ),
    ]
