# Generated by Django 2.2.1 on 2019-10-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0004_auto_20191003_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientguidelines',
            old_name='Patient',
            new_name='patient',
        ),
    ]
