# Generated by Django 2.1.2 on 2018-12-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('cno', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=100)),
            ],
        ),
    ]
