# Generated by Django 2.2.1 on 2019-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app30', '0002_auto_20190716_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
