# Generated by Django 2.2.4 on 2019-09-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('faculty_name', models.CharField(max_length=30)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=7)),
                ('time', models.TimeField()),
            ],
        ),
    ]
