# Generated by Django 2.1.10 on 2019-07-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PankajApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromModelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('email_address', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('is_active', models.CharField(max_length=1)),
                ('login_id', models.PositiveIntegerField()),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('created_by', models.PositiveIntegerField()),
                ('creation_date', models.DateField(blank=True)),
                ('last_updated_by', models.PositiveIntegerField()),
                ('last_updated_date', models.DateField(blank=True)),
                ('attribute1', models.CharField(max_length=255)),
                ('attribute2', models.CharField(max_length=255)),
                ('attribute3', models.CharField(max_length=255)),
                ('attribute4', models.CharField(max_length=255)),
                ('attribute5', models.CharField(max_length=255)),
                ('attribute6', models.CharField(max_length=255)),
                ('attribute7', models.CharField(max_length=255)),
                ('attribute8', models.CharField(max_length=255)),
                ('attribute9', models.CharField(max_length=255)),
                ('attribute10', models.CharField(max_length=255)),
            ],
        ),
    ]
